version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcde         # Change to a secure password
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    restart: always
    environment:
      DB_USER: inventory_user
      DB_PASSWORD: inventory_pass
      DB_HOST: mysql              # This refers to the mysql service defined below
      DB_NAME: inventory_db
      SECRET_KEY: your_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    dns:
      - 8.8.8.8

volumes:
  mysql_data:
